name: docker
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: success()  && github.event_name == 'pull_request' # trigger only a build on PR's.
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: cboin/songbirdweb:latest
          cache-from: type=registry,ref=cboin/songbirdweb:buildcache
          cache-to: type=registry,ref=cboin/songbirdweb:buildcache,mode=max
      - name: Build and Push
        if: success() && (github.event_name == 'push' || startsWith(github.ref, 'refs/tags/'))  # only trigger a build and push to docker registry on tag or commit sha off
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cboin/songbirdweb:latest
          cache-from: type=registry,ref=cboin/songbirdweb:buildcache
          cache-to: type=registry,ref=cboin/songbirdweb:buildcache,mode=max

